name: Factory pattern CI
on: [ push, pull_request ]

jobs:
    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-node@3
              with:
                node-version: 16.x
            - run: |
                yarn install
                yarn test
